### ISSUE TITLE
How to set some textures to the material?

### ISSUE THREAD

**Issue by vimcaw** [brianzinn/react-babylonjs#44]
Hi Brian, thanks for your kind help before. I try to set some textures to the material but get some errors, I have tried to find any demo but get nothing, Is there something wrong with my approach?

```jsx
<Box
  name="ground"
  width={size}
  depth={size}
  height={thickness}
>
  <StandardMaterial
    name="ground material"
    useParallax
    useParallaxOcclusion
    specularColor={new Color4(0.9, 0.9, 0.9, 0.5)}
    position={Vector3.Zero()}
  >
    <diffuseTexture uScale={50} vScale={50} url="http://localhost:8666/texture/floor.jpg" />
    <bumpTexture uScale={50} vScale={50} url="http://localhost:8666/texture/floor_bump.jpg" />
    <reflectionTexture
      mirrorPlane={new Plane(0, -1.0, 0, -2.0)}
      level={0.1}
      reflectionTexture={10}
    />
  </StandardMaterial>
</Box>
```
Error: 
```
Uncaught Error: Cannot generate type 'diffuseTexture/diffuseTexture' inside 'react-babylonjs' (ie: no DOM rendering on HTMLCanvas)
```

**Comment by brianzinn** [comment]
That's because 'diffuseTexture' is not valid.  You need to create a `texture` and use a new property `assignTo`.  Here is a story:
https://github.com/brianzinn/react-babylonjs/blob/master/stories/babylonjs/7-textures/image-texture.stories.js

It's not on NPM yet, but will look like this:
```jsx
<Box
  name="ground"
  width={size}
  depth={size}
  height={thickness}
>
  <StandardMaterial
    name="ground material"
    useParallax
    useParallaxOcclusion
    specularColor={new Color4(0.9, 0.9, 0.9, 0.5)}
    position={Vector3.Zero()}
  >
    <texture uScale={50} vScale={50} url="http://localhost:8666/texture/floor.jpg" />
    <texture assignTo="bump" uScale={50} vScale={50} url="http://localhost:8666/texture/floor_bump.jpg" />
    <texture
      assignTo="reflection"
      mirrorPlane={new Plane(0, -1.0, 0, -2.0)}
      level={0.1}
      reflectionTexture={10}
    />
  </StandardMaterial>
</Box>
```

Diffuse will be assigned by default.  Here is an example that I just tested with `bumpTexture`:
![image](https://user-images.githubusercontent.com/542756/75956208-3f516800-5e6c-11ea-9883-30c9f7b8fd6d.png)

I'll drop a note here when I get the NPM out.  There are a bunch of things that need to be tested as there are a lot of new changes on master branch - should have it for Saturday :)

**Comment by vimcaw** [comment]
Thank you again! 😀 

I'm curious what is the online URL of your Storybook (not source code, but preview), I only found this short version of the Storybook in README.md: https://brianzinn.github.io/react-babylonjs/?path=/story/babylon-basic--default-playground

**Comment by brianzinn** [comment]
I don’t have a preview. I need to manually update storybook by pushing to github pages    

If you download this repo, you can
1. Yarn install
2. Yarn build
3. Yarn storybook

That was how I did the screenshot!

**Comment by vimcaw** [comment]
Got it, I think I can learn a lot from it.

**Comment by vimcaw** [comment]
@brianzinn Unluckily, I still meet an error, and it also appears on the storybook example you provided (I get an error when trying to build storybook of this repo, so I made the codesandbox demo): https://codesandbox.io/s/texture-problem-381bm

Error: 

![image](https://user-images.githubusercontent.com/21964227/76046275-6dcd6100-5f9a-11ea-8404-53db1b5b6811.png)

```
Skybox specific code.  Assigning reflection texture.  Need custom properties to define which texture/coordinatesMode to apply 
t {metadata: null, reservedDataStore: null, _hasAlpha: true, getAlphaFromRGB: false, level: 1…}
5

    in Anonymous (created by Context.Consumer)
    in Context.Consumer (created by Anonymous)
    in Anonymous (at App.js:16)
    in App (at src/​index.js:9)
```

The official example is normal: https://www.babylonjs-playground.com/#YDO1F#75

When I try to build the storybook (`yarn storybook`), I throw an error:

```
ERROR in ./dist/react-babylonjs.es5.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /Users/vimcaw/Downloads/react-babylonjs-master/dist/react-babylonjs.es5.js: Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null
    at Object.validate (/Users/vimcaw/Downloads/react-babylonjs-master/node_modules/@babel/types/lib/definitions/utils.js:131:11)
    at validateField (/Users/vimcaw/Downloads/react-babylonjs-master/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at Object.validate (/Users/vimcaw/Downloads/react-babylonjs-master/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at NodePath._replaceWith (/Users/vimcaw/Downloads/react-babylonjs-master/node_modules/@babel/traverse/lib/path/replacement.js:172:7)
    at NodePath._remove (/Users/vimcaw/Downloads/react-babylonjs-master/node_modules/@babel/traverse/lib/path/removal.js:55:10)
    at NodePath.remove (/Users/vimcaw/Downloads/react-babylonjs-master/node_modules/@babel/traverse/lib/path/removal.js:34:8)
    at hooks (/Users/vimcaw/Downloads/react-babylonjs-master/node_modules/@babel/traverse/lib/path/lib/removal-hooks.js:11:12)
    at NodePath._callRemovalHooks (/Users/vimcaw/Downloads/react-babylonjs-master/node_modules/@babel/traverse/lib/path/removal.js:46:9)
    at NodePath.remove (/Users/vimcaw/Downloads/react-babylonjs-master/node_modules/@babel/traverse/lib/path/removal.js:26:12)
    at convertFunctionParams (/Users/vimcaw/Downloads/react-babylonjs-master/node_modules/@babel/plugin-transform-parameters/lib/params.js:88:30)
    at PluginPass.Function (/Users/vimcaw/Downloads/react-babylonjs-master/node_modules/@babel/plugin-transform-parameters/lib/index.js:30:53)
    at newFn (/Users/vimcaw/Downloads/react-babylonjs-master/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/Users/vimcaw/Downloads/react-babylonjs-master/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/vimcaw/Downloads/react-babylonjs-master/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/vimcaw/Downloads/react-babylonjs-master/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/Users/vimcaw/Downloads/react-babylonjs-master/node_modules/@babel/traverse/lib/context.js:112:16)
 @ ./stories/babylonjs/1-basic/dragNdrop.stories.js 46:0-66 127:29-35 134:25-30
 @ ./stories sync \.stories\.js$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```

**Comment by brianzinn** [comment]
I suspect it hasn’t built properly before storybook started. ie: ‘yarn build’ failed for you

Your codesandbox example should run on the next NPM. There are lots of code changes on master that aren’t out yet on NPM. I ran a bunch of tests yesterday and will do a release on Saturday.

**Comment by vimcaw** [comment]
![image](https://user-images.githubusercontent.com/21964227/76133995-3623ef00-6056-11ea-869f-b1cdf3f37352.png)
Is the `(!) Missing global variable names` a problem?

**Comment by brianzinn** [comment]
I get that warning as well. If that is a clean copy of master (no local code changes) - what version of compiler and what commit hash are you on? Also, do you see anything odd in ./dist/react-babylonjs.es5.js?

**Comment by vimcaw** [comment]
Yeah, it's clean, I don't change anything.

* yarn version: 1.22.0
* node.js version: 12.14.0
* npm version: 6.13.4
* commit hash: ea0c1803136669d96eacfba50ce095e146db6951

I think it's because our dependency versions are different, this project only has `package-lock.json` file but hasn't `yarn.lock` file.

This's my `yarn.lock` file:
[yarn.lock.txt](https://github.com/brianzinn/react-babylonjs/files/4301601/yarn.lock.txt)

The `dist` folder tree:
```
.
├── react-babylonjs.es5.js
├── react-babylonjs.es5.js.map
├── react-babylonjs.umd.js
├── react-babylonjs.umd.js.map
└── types
    ├── BasePropsHandler.d.ts
    ├── CreatedInstance.d.ts
    ├── Engine.d.ts
    ├── LifecycleListener.d.ts
    ├── PropsHandler.d.ts
    ├── ReactBabylonJSHostConfig.d.ts
    ├── Scene.d.ts
    ├── UpdateInstance.d.ts
    ├── codeGenerationDescriptors.d.ts
    ├── customComponents
    │   ├── AdvancedDynamicTextureLifecycleListener.d.ts
    │   ├── CameraLifecycleListener.d.ts
    │   ├── EnvironmentHelperLifecycleListener.d.ts
    │   ├── GUI2DControlLifecycleListener.d.ts
    │   ├── GUI3DControlLifecycleListener.d.ts
    │   ├── GUI3DManagerLifecycleListener.d.ts
    │   ├── MaterialsLifecycleListener.d.ts
    │   ├── ModelLifecycleListener.d.ts
    │   ├── NodeLifecycleListener.d.ts
    │   ├── PhysicsImpostorLifecycleListener.d.ts
    │   ├── ShadowGeneratorLifecycleListener.d.ts
    │   ├── Skybox.d.ts
    │   ├── TargetPropsHandler.d.ts
    │   ├── TexturesLifecycleListener.d.ts
    │   ├── VRExperienceHelperLifecycleListener.d.ts
    │   └── index.d.ts
    ├── customHosts
    │   ├── hostWithEventsFiber.d.ts
    │   └── index.d.ts
    ├── extensions
    │   ├── DynamicTerrain.d.ts
    │   └── index.d.ts
    ├── generatedCode.d.ts
    ├── generatedProps.d.ts
    ├── hooks.d.ts
    ├── model
    │   ├── Model.d.ts
    │   ├── ModelProps.d.ts
    │   └── index.d.ts
    ├── react-babylonjs.d.ts
    └── utils
        └── property.unit.d.ts

6 directories, 41 files
```

**Comment by brianzinn** [comment]
I was unable to reproduce your error.  Have a look at this storybook:
https://brianzinn.github.io/react-babylonjs/?path=/story/textures--image-texture
The storybook source is here:
https://github.com/brianzinn/react-babylonjs/blob/master/stories/babylonjs/7-textures/image-texture.stories.js

Can you try against 2.0.4, which was just published?

**Comment by vimcaw** [comment]
After upgrading to `2.0.4`, it works perfectly! Thank you again!
